#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import os, sys
from kconfiglib import *
from menuconfig import menuconfig as mc
import argparse


def genconfig(kconf, directory):
    os.environ["KCONFIG_CONFIG"] = os.path.join("kconfig")
    os.environ["KCONFIG_CONFIG_HEADER"] = "# Generated by My Kconfig Demo"
    os.environ["KCONFIG_AUTOHEADER"] = os.path.join("kconfig.h")
    os.environ["CONFIG "] = ""
    kconf.write_autoconf()

def menuconfig(kconf, directory):
    os.environ["MENUCONFIG_STYLE"] = "default selection=fg:white,bg:blue"
    mc(kconf)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('-m', '--menuconfig', action='store_true', help='')
    parser.add_argument('-g', '--generateconfig', action='store_true', help='')
    parser.add_argument('-d', '--directory', help='work directory', required=True)
    args = parser.parse_args()
    file = args.directory + "/kconfig"
    kconf = Kconfig(filename = file)
    if args.menuconfig:
        menuconfig(kconf, args.directory)
    elif args.generateconfig:
        genconfig(kconf, args.directory)
     

if __name__== "__main__":
    main()